---
name: publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: nightly-2024-12-14

jobs:
  publish-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    env:
      QUANTUS_CDN_KEY: ${{ secrets.QUANTUS_CDN_KEY }}
    steps:
      -
        uses: actions/checkout@v4
      -
        if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/disk
      -
        if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/ubuntu
      -
        if: contains(matrix.os, 'macos')
        uses: ./.github/actions/macos
      -
        name: pin
        run: rustup override set ${RUSTUP_TOOLCHAIN}
      -
        name: cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      -
        name: compile
        run: cargo build --locked --release --workspace
        timeout-minutes: 90
      -
        if: contains(matrix.os, 'macos')
        name: publish
        run: |
          mkdir -p ~/.ssh
          echo ${QUANTUS_CDN_KEY} > ~/.ssh/id_quantus
          chmod 600 ~/.ssh/id_quantus
          mkdir -p ./${GITHUB_SHA:0:11}/osx
          cp target/release/quantus-node ./${GITHUB_SHA:0:11}/osx/quantus-node
          cp target/release/external-miner ./${GITHUB_SHA:0:11}/osx/quantus-miner
          rsync \
            --archive \
            --compress \
            --rsh 'ssh -i ~/.ssh/id_quantus -o ConnectTimeout=3 -p 52201' \
            --verbose \
            ./${GITHUB_SHA:0:11} \
            resonance@cdn.res.fm:/usr/share/nginx/cdn.res.fm/release/
        timeout-minutes: 1
      -
        if: contains(matrix.os, 'ubuntu')
        name: publish
        run: |
          mkdir -p ~/.ssh
          echo ${QUANTUS_CDN_KEY} > ~/.ssh/id_quantus
          chmod 600 ~/.ssh/id_quantus
          mkdir -p ./${GITHUB_SHA:0:11}/linux
          cp target/release/quantus-node ./${GITHUB_SHA:0:11}/linux/quantus-node
          cp target/release/external-miner ./${GITHUB_SHA:0:11}/linux/quantus-miner
          rsync \
            --archive \
            --compress \
            --rsh 'ssh -i ~/.ssh/id_quantus -o ConnectTimeout=3 -p 52201' \
            --verbose \
            ./${GITHUB_SHA:0:11} \
            resonance@cdn.res.fm:/usr/share/nginx/cdn.res.fm/release/
        timeout-minutes: 1
